In [1]:
import pandas as pd
import numpy as np


In [5]:
# Merge Maoyan and Douban
data = []
maoyan = pd.read_excel("Data/Maoyan_comment.xlsx")
douban = pd.read_excel("Data/Douban_comment.xlsx")

# Remove the rows with unknown score
print(douban['评分'].unique())
# Remove the rows with unknown score and 0 score
douban = douban[douban['评分'] != 'unknown']
douban = douban[douban['评分'] != 0]

# Change the score to int
douban['评分'] = douban['评分'].astype(int)
maoyan['评分'] = maoyan['评分'].astype(int)

# Merge two dataframes
data.append(maoyan)
data.append(douban)
df = pd.concat(data)
df.to_excel("Data/Comment.xlsx", index=False)

print(douban['评分'].unique())
print(maoyan['评分'].unique())
print(df['评分'].unique())

[5 3 4 2 1 'unknown' 0]
[5 3 4 2 1]
[5 4 3 2 0 1]
[5 4 3 2 0 1]


In [6]:
# score>3 is positive, score< 3 is negative
positive = df[df['评分'] > 3]
negative = df[df['评分'] < 3]
# Only keep the comment and score
# remove comment content with less than 3 characters
positive = positive[positive['评论内容'].str.len() > 3]
negative = negative[negative['评论内容'].str.len() > 3]

positive = positive[['评论内容']]
negative = negative[['评论内容']]

positive.to_excel("Data/pos.xlsx", index=False)
negative.to_excel("Data/neg.xlsx", index=False)

# Export to txt
positive.to_csv("Data/pos.txt", index=False, header=False, sep='\t')
negative.to_csv("Data/neg.txt", index=False, header=False, sep='\t')
